/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ThreadTraceView.java
 *
 * Created on Nov 7, 2011, 9:50:26 AM
 */
package org.perfmon4j.visualvm;

import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import org.perfmon4j.visualvm.chart.ThreadTraceList;

/**
 *
 * @author ddeucher
 */
public class ThreadTraceViewDlg extends javax.swing.JDialog {

    /** Creates new form ThreadTraceView */
    public ThreadTraceViewDlg(java.awt.Frame parent, ThreadTraceList.ThreadTraceElement element) {
        super(parent, true);
        initComponents();
        
        SimpleDateFormat f = new SimpleDateFormat("MM/dd HH:mm:ss");
        timeField.setText(f.format(element.getTimeSubmitted()));
        monitorField.setText(element.getFieldKey().getMonitorKey().getName());
        threadTraceText.setText(element.getResult());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        timeField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        monitorField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        threadTraceText = new javax.swing.JTextArea();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText(org.openide.util.NbBundle.getMessage(ThreadTraceViewDlg.class, "ThreadTraceViewDlg.jLabel1.text")); // NOI18N

        timeField.setText(org.openide.util.NbBundle.getMessage(ThreadTraceViewDlg.class, "ThreadTraceViewDlg.timeField.text")); // NOI18N
        timeField.setEnabled(false);
        timeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeFieldActionPerformed(evt);
            }
        });

        jLabel2.setText(org.openide.util.NbBundle.getMessage(ThreadTraceViewDlg.class, "ThreadTraceViewDlg.jLabel2.text")); // NOI18N

        monitorField.setText(org.openide.util.NbBundle.getMessage(ThreadTraceViewDlg.class, "ThreadTraceViewDlg.monitorField.text")); // NOI18N

        threadTraceText.setColumns(20);
        threadTraceText.setEditable(false);
        threadTraceText.setRows(5);
        jScrollPane1.setViewportView(threadTraceText);

        closeButton.setText(org.openide.util.NbBundle.getMessage(ThreadTraceViewDlg.class, "ThreadTraceViewDlg.closeButton.text")); // NOI18N
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(timeField, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(monitorField, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(closeButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(timeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(monitorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(closeButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void timeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeFieldActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    
    public static void showModel(JFrame parent, ThreadTraceList.ThreadTraceElement element) {
        ThreadTraceViewDlg dialog = new ThreadTraceViewDlg(parent, element);
        dialog.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        dialog.pack();
        dialog.setLocationRelativeTo(parent);
        dialog.setVisible(true);
    }    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField monitorField;
    private javax.swing.JTextArea threadTraceText;
    private javax.swing.JTextField timeField;
    // End of variables declaration//GEN-END:variables
}
