/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ThreadTraceOptions.java
 *
 * Created on Nov 9, 2011, 4:31:29 PM
 */
package org.perfmon4j.visualvm;

import java.util.HashMap;
import java.util.Map;
import javax.swing.JFrame;
import org.perfmon4j.remotemanagement.intf.FieldKey;

/**
 *
 * @author ddeucher
 */
public class ThreadTraceOptions extends javax.swing.JDialog {
    private Map<String, String> result = null;
    
    /** Creates new form ThreadTraceOptions */
    public ThreadTraceOptions(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
    }

    private static ThreadTraceOptions dialog = null;
    
    public static Map<String, String> showModel(JFrame parent) {
        if (dialog == null) {
            dialog = new ThreadTraceOptions(parent);
        }
        dialog.result = null;
        
        dialog.setDefaultCloseOperation(HIDE_ON_CLOSE);
        dialog.pack();
        dialog.setLocationRelativeTo(parent);        
        dialog.setVisible(true);

        return dialog.result;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        minDurationToCaptureField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        maxDepthField = new javax.swing.JTextField();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText(org.openide.util.NbBundle.getMessage(ThreadTraceOptions.class, "ThreadTraceOptions.jLabel1.text")); // NOI18N

        minDurationToCaptureField.setText(org.openide.util.NbBundle.getMessage(ThreadTraceOptions.class, "ThreadTraceOptions.minDurationToCaptureField.text")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(ThreadTraceOptions.class, "ThreadTraceOptions.jLabel2.text")); // NOI18N

        maxDepthField.setText(org.openide.util.NbBundle.getMessage(ThreadTraceOptions.class, "ThreadTraceOptions.maxDepthField.text")); // NOI18N

        okButton.setText(org.openide.util.NbBundle.getMessage(ThreadTraceOptions.class, "ThreadTraceOptions.okButton.text")); // NOI18N
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText(org.openide.util.NbBundle.getMessage(ThreadTraceOptions.class, "ThreadTraceOptions.cancelButton.text")); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(okButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelButton))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(maxDepthField)
                        .addComponent(minDurationToCaptureField, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(minDurationToCaptureField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxDepthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancelButton))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        result = new HashMap<String, String>();
        String maxDepth = maxDepthField.getText();
        String minDur = minDurationToCaptureField.getText();
        
        if (maxDepth != null && !"".equals(maxDepth)) {
            // TODO should check for non-numeric and or negative values...
            result.put(FieldKey.THREAD_TRACE_MAX_DEPTH_ARG, maxDepth);
        }
        
        if (minDur != null && !"".equals(minDur)) {
            // TODO should check for non-numeric and or negative values...
            result.put(FieldKey.THREAD_TRACE_MIN_DURATION_ARG, minDur);
        }
        dialog.setVisible(false);
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dialog.result = null;
        dialog.setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThreadTraceOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThreadTraceOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThreadTraceOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThreadTraceOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                ThreadTraceOptions dialog = new ThreadTraceOptions(new javax.swing.JFrame());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField maxDepthField;
    private javax.swing.JTextField minDurationToCaptureField;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
}
