/*
 *	Copyright 2011-2012 Follett Software Company 
 *
 *	This file is part of PerfMon4j(tm).
 *
 * 	Perfmon4j is free software: you can redistribute it and/or modify
 * 	it under the terms of the GNU Lesser General Public License, version 3,
 * 	as published by the Free Software Foundation.  This program is distributed
 * 	WITHOUT ANY WARRANTY OF ANY KIND, WITHOUT AN IMPLIED WARRANTY OF MERCHANTIBILITY,
 * 	OR FITNESS FOR A PARTICULAR PURPOSE.  You should have received a copy of the GNU Lesser General Public 
 * 	License, Version 3, along with this program.  If not, you can obtain the LGPL v.s at 
 * 	http://www.gnu.org/licenses/
 * 	
 * 	perfmon4j@fsc.follett.com
 * 	David Deuchert
 * 	Follett Software Company
 * 	1391 Corporate Drive
 * 	McHenry, IL 60050
 * 
*/
package org.perfmon4j.visualvm;

import java.util.HashMap;
import java.util.Map;
import org.perfmon4j.remotemanagement.intf.FieldKey;
import org.perfmon4j.remotemanagement.intf.MonitorKey;

/**
 *
 * @author ddeucher
 */
public class ThreadTraceOptionsDlg extends javax.swing.JDialog {
    private Map<String, String> result = null;

    // Index-aligned with triggerTypeComboBox's model. Index 0 ("(none)") has no
    // corresponding prefix -- no trigger is attached in that case.
    private static final String[] TRIGGER_TYPE_LABELS = {
        "(none)", "Request Parameter", "Session Attribute", "Cookie"
    };
    private static final String[] TRIGGER_TYPE_PREFIXES = {
        null, "HTTP", "HTTP_SESSION", "HTTP_COOKIE"
    };

    /** Creates new form ThreadTraceOptions */
    public ThreadTraceOptionsDlg(MainWindow mainWindow) {
        super(mainWindow.getParentFrame(), true);
        initComponents();
    }
    
    public static void doScheduleThreadTrace(MainWindow mainWindow,
            MonitorKey key) {
        
        if (mainWindow.threadTraceOptionsDlg == null) {
            mainWindow.threadTraceOptionsDlg = new ThreadTraceOptionsDlg(mainWindow);
        }
        ThreadTraceOptionsDlg dlg = mainWindow.threadTraceOptionsDlg;
        
        dlg.result = null;
        dlg.triggerTypeComboBox.setSelectedIndex(0);
        dlg.triggerNameField.setText("");
        dlg.triggerValueField.setText("");

        dlg.monitorNameTextField.setText(key.getName());
        dlg.setDefaultCloseOperation(HIDE_ON_CLOSE);
        dlg.pack();
        dlg.setLocationRelativeTo(mainWindow.getParentFrame());        
        dlg.setVisible(true);

        if (dlg.result != null) {
            mainWindow.getFieldManager().scheduleThreadTrace(key, dlg.result);
            mainWindow.bringThreadTraceWindowToFront();
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        monitorNameTextField = new javax.swing.JTextField();
        minDurationToCaptureField = new javax.swing.JFormattedTextField();
        maxDepthField = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        triggerTypeComboBox = new javax.swing.JComboBox<String>(TRIGGER_TYPE_LABELS);
        triggerNameField = new javax.swing.JTextField();
        triggerValueField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(org.openide.util.NbBundle.getMessage(ThreadTraceOptionsDlg.class, "ThreadTraceOptionsDlg.title")); // NOI18N
        setResizable(false);

        jLabel1.setText(org.openide.util.NbBundle.getMessage(ThreadTraceOptionsDlg.class, "ThreadTraceOptionsDlg.jLabel1.text")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(ThreadTraceOptionsDlg.class, "ThreadTraceOptionsDlg.jLabel2.text")); // NOI18N

        okButton.setText(org.openide.util.NbBundle.getMessage(ThreadTraceOptionsDlg.class, "ThreadTraceOptionsDlg.okButton.text")); // NOI18N
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText(org.openide.util.NbBundle.getMessage(ThreadTraceOptionsDlg.class, "ThreadTraceOptionsDlg.cancelButton.text")); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel3.setText(org.openide.util.NbBundle.getMessage(ThreadTraceOptionsDlg.class, "ThreadTraceOptionsDlg.jLabel3.text")); // NOI18N

        monitorNameTextField.setEditable(false);
        monitorNameTextField.setText(org.openide.util.NbBundle.getMessage(ThreadTraceOptionsDlg.class, "ThreadTraceOptionsDlg.monitorNameTextField.text")); // NOI18N

        minDurationToCaptureField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###"))));
        minDurationToCaptureField.setText(org.openide.util.NbBundle.getMessage(ThreadTraceOptionsDlg.class, "ThreadTraceOptionsDlg.minDurationToCaptureField.text")); // NOI18N

        maxDepthField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        jLabel4.setText(org.openide.util.NbBundle.getMessage(ThreadTraceOptionsDlg.class, "ThreadTraceOptionsDlg.jLabel4.text")); // NOI18N

        jLabel5.setText(org.openide.util.NbBundle.getMessage(ThreadTraceOptionsDlg.class, "ThreadTraceOptionsDlg.jLabel5.text")); // NOI18N

        jLabel6.setText(org.openide.util.NbBundle.getMessage(ThreadTraceOptionsDlg.class, "ThreadTraceOptionsDlg.jLabel6.text")); // NOI18N

        triggerNameField.setEnabled(false);

        triggerValueField.setEnabled(false);

        triggerTypeComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                triggerTypeComboBoxItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(monitorNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(maxDepthField, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                            .addComponent(minDurationToCaptureField, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(triggerTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(triggerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(triggerValueField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(okButton)
                        .addGap(10, 10, 10)
                        .addComponent(cancelButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(monitorNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(minDurationToCaptureField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(maxDepthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(triggerTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(triggerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(triggerValueField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancelButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        result = new HashMap<String, String>();
        String maxDepth = maxDepthField.getText();
        String minDur = minDurationToCaptureField.getText();
        
        if (maxDepth != null && !"".equals(maxDepth)) {
            // TODO should check for non-numeric and or negative values...
            result.put(FieldKey.THREAD_TRACE_MAX_DEPTH_ARG, maxDepth);
        }
        
        if (minDur != null && !"".equals(minDur)) {
            // TODO should check for non-numeric and or negative values...
            result.put(FieldKey.THREAD_TRACE_MIN_DURATION_ARG, minDur);
        }

        int triggerTypeIndex = triggerTypeComboBox.getSelectedIndex();
        String triggerTypePrefix = triggerTypeIndex >= 0 ? TRIGGER_TYPE_PREFIXES[triggerTypeIndex] : null;
        String triggerName = triggerNameField.getText();
        String triggerValue = triggerValueField.getText();
        if (triggerTypePrefix != null && triggerName != null && !"".equals(triggerName)
                && triggerValue != null && !"".equals(triggerValue)) {
            result.put(FieldKey.THREAD_TRACE_TRIGGER_ARG,
                    FieldKey.encodeTriggerArg(triggerTypePrefix, triggerName, triggerValue));
        }

        this.setVisible(false);
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.result = null;
        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void triggerTypeComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_triggerTypeComboBoxItemStateChanged
        boolean triggerSelected = triggerTypeComboBox.getSelectedIndex() > 0;
        triggerNameField.setEnabled(triggerSelected);
        triggerValueField.setEnabled(triggerSelected);
    }//GEN-LAST:event_triggerTypeComboBoxItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JFormattedTextField maxDepthField;
    private javax.swing.JFormattedTextField minDurationToCaptureField;
    private javax.swing.JTextField monitorNameTextField;
    private javax.swing.JButton okButton;
    private javax.swing.JComboBox<String> triggerTypeComboBox;
    private javax.swing.JTextField triggerNameField;
    private javax.swing.JTextField triggerValueField;
    // End of variables declaration//GEN-END:variables
}
