name: Feature branch test

on:
  push:
    branches: ['feature/**']

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DEVELOP_OR_MASTER: | 
          ${{ endsWith(github.ref, '/develop') 
          || endsWith(github.ref, '/feature/PublishArtifactsToGitHub')}}
    steps:
      - name: Checking out the code
        uses: actions/checkout@v2

      - name: Setting up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

#      - name: Run Maven Build
#        run: mvn -B compile --file pom.xml

#      - name: Run Maven Test
#        run: mvn -B test --file pom.xml

      - name: Assemble release artifacts
        if: ${{ env.DEVELOP_OR_MASTER }}
        run: mvn -B assembly:assembly -DskipTests

      - name: Publish assembly artifacts
        if:  ${{ env.DEVELOP_OR_MASTER }}
        uses: actions/upload-artifact@v2
        with:
          name: "Assembled-binary-and-source-zip-files"
          path: "./target/perfmon4j*.zip"
